### ISSUE TITLE
Homepage URL 404s

### ISSUE THREAD

**Issue by cassidyjames** [jhaygood86/big-purple-remote#1]
Looks like there's nothing here:

https://github.com/jhaygood86/big-purple-remote/blob/04a2f6c3a0af1abce2a9e1f41562b96d2a7b81cf/data/io.github.jhaygood86.big-purple-remote.appdata.xml.in#L65

**Comment by jhaygood86** [comment]
This should be fixed now. Forgot to actually publish it...
